/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    extend: {
      fontFamily: {
        monstserrat: ["Montserrat", "sans-serif"],
        lato: ["Lato", "sans-serif"],
        pcq: ["Roboto", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        "josefin-sans": ["Josefin\\ Sans", "sans-serif"],
        raleway: ["Raleway", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        "open-sans": ["Open\\ Sans", "sans-serif"],
        "roboto-condensed": ["Roboto\\ Condensed", "sans-serif"],
        "roboto-slab": ["Roboto\\ Slab", "serif"],
        "open-sans-condensed": ["Open\\ Sans\\ Condensed", "sans-serif"],
        sans: ["Josefina\\ Sans", "sans-serif"],
        serif: ["Roboto\\ Slab", "serif"],
        poppins: ["Poppins", "sans-serif"],
        courier: ["Courier\\ Prime", "monospace"],
        mono: ["Roboto\\ Mono", "monospace"],
      },
      aspectRatio: {
        cuadrado: "1 / 1",
        vertical: "4 / 5",
        banner: "4 / 3",
        destacados: "16 / 9",
        poster: "2 / 3",
        fondo: "26 / 10",
      },
      spacing: {
        small: "8px",
        normal: "16px",
        medium: "32px",
        large: "64px",
        larger: "28rem",
        largest: "32rem",
        giant: "48rem",
      },
      colors: {
        "color-texto": "#FFFFFF",
        "color-bono": "#0061a8",
        "color-accent": "#2d2d2d",
        "color-contra": "#2d2d2d",
        "color-fondo": "#0061a8",
        "color-boton-texto": "#ffffff",
        "bono-home": "#0061a8",
        "bono-bizkaia": "#BF0811",
        "bono-gipuzkoa": "#15B2D3",
        "bono-denda": "#CECFDF",
      },
    },
  },
  plugins: [require("daisyui"), require("@tailwindcss/aspect-ratio")],
};
